- name: Wait for apt lock to be released
  shell: while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 1; done
  changed_when: false
  failed_when: false

- name: Install dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
  retries: 5
  delay: 10
  register: install_deps_result
  until: install_deps_result is succeeded

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Remove legacy Docker GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: absent
  failed_when: false

- name: Remove old Docker repository files
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Check if Docker GPG key exists
  stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker_gpg_key

- name: Download and install Docker GPG key
  block:
    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /tmp/docker.gpg
        mode: '0644'
      retries: 5
      delay: 10
      
    - name: Convert and install GPG key
      shell: |
        gpg --dearmor < /tmp/docker.gpg > /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      
    - name: Clean up temporary file
      file:
        path: /tmp/docker.gpg
        state: absent
  when: not docker_gpg_key.stat.exists

- name: Add Docker APT repository (single entry)
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    mode: '0644'

- name: Update apt cache after adding repository
  apt:
    update_cache: true
  retries: 5
  delay: 10
  register: cache_update_result
  until: cache_update_result is succeeded

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    install_recommends: false
  retries: 5
  delay: 10
  register: docker_install_result
  until: docker_install_result is succeeded

- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: true