---
# defaults file for roles/deb-os-update
# Type  of upgrade apt : 'safe' (upgrade), 'full' (full-upgrade) or 'dist' (dist-upgrade).
os_upgrade_type: "dist"

# Avoid interactive prompts and keep local configs.
os_dpkg_options: "force-confdef,force-confold"

# Avoid reloading the index too often.
os_cache_valid_time: 3600

# Clean after upgrade
os_autoremove: true
os_autoclean: true

# Reboot if necessary (kernel, libc, etc.)
os_reboot_if_required: true
os_reboot_timeout: 600

# Reboot control while upgrade
os_needrestart_mode: "a"  # a = auto (redémarre les services touchés)
